;; elisp.org -- loads configuration files (*.el) contained in this folder

* Add load path

Tell emacs to look in these folders for emacs-lisp (*.el) files:

#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "~/.emacs.d/emacs-config/elisp/")
  (add-to-list 'load-path "~/.emacs.d/emacs-config/elisp/rust-mode")
#+END_SRC

`my-require' is used throughout this file.  Requiring it here rather
than relying on emacs-config.org to have defined it matters: this file
is loaded in place from the repository, so a git pull updates it, while
emacs-config.org only reaches ~/.emacs.d when install.sh copies it.
Pulling without installing would otherwise leave the calls below with
no definition.

#+BEGIN_SRC emacs-lisp
  (require 'my-require)
#+END_SRC


* Mode settings

** cmake-mode

Load the cmake-mode.el configuration file obtained from:
https:/github.com/Kitware/CMake/blob/master/Auxiliary/cmake-mode.el

#+BEGIN_SRC emacs-lisp
  (my-require 'cmake-mode)
#+END_SRC

** yaml-mode

Load the yaml-mode.el configuration file obtained from:
https://github.com/yoshiki/yaml-mode/blob/master/yaml-mode.el

#+BEGIN_SRC emacs-lisp
  (my-require 'yaml-mode)
#+END_SRC

We'll also define a hook to define a yaml-mode specific key binding.

#+BEGIN_SRC emacs-lisp
  (add-hook 'yaml-mode-hook
      (lambda ()
         (define-key yaml-mode-map "\C-m" 'newline-and-indent)))
#+END_SRC

** org-mode

Use fancy-style bullets for org-mode.

#+BEGIN_SRC emacs-lisp
  (when (my-require 'org-bullets)
    (add-hook 'org-mode-hook
              (lambda () (org-bullets-mode 1))))
#+END_SRC

Use template expansion for org-structures.

#+BEGIN_SRC emacs-lisp
;;  (require 'org-tempo)
#+END_SRC

Require ox-rst for porting org-mode to ReST format

#+BEGIN_SRC emacs-lisp
  (my-require 'ox-rst)
#+END_SRC

** kpp-mode

Load kpp.el configuration file obtained from the KPP repository

#+BEGIN_SRC emacs-lisp
  (my-require 'kpp)
#+END_SRC

** rust-mode

Load the Rust major mode.

#+BEGIN_SRC emacs-lisp
  (my-require 'rust-mode)
;autoload 'rust-mode "rust-mode" nil t)
#+END_SRC

Insert spaces instead of tabs, as per the Rust style guide.

#+BEGIN_SRC emacs-lisp
  (add-hook 'rust-mode-hook
            (lambda () (setq indent-tabs-mode nil)))
#+END_SRC

Enable auto-formatting when saving a Rust source code file.

#+BEGIN_SRC emacs-lisp
  (setq rust-format-on-save t)
#+END_SRC

Toggle "prettifying" of symbols

#+BEGIN_SRC emacs-lisp
  (add-hook 'rust-mode-hook
            (lambda () (prettify-symbols-mode)))
#+END_SRC


* Terminal settings

Load 256 color options for terminal mode.

#+BEGIN_SRC emacs-lisp
  ;;(require 'eterm-256color)
  (my-require 'xterm-color)
#+END_SRC
